version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=knest_db
      - POSTGRES_USER=knest_user
      - POSTGRES_PASSWORD=knest_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=knest_backend.settings.development
      - DATABASE_URL=postgres://knest_user:knest_password@db:5432/knest_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A knest_backend worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=knest_backend.settings.development
      - DATABASE_URL=postgres://knest_user:knest_password@db:5432/knest_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

volumes:
  postgres_data: 