# Generated by Django 4.2.22 on 2025-06-12 16:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationExperiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="実験名")),
                ("description", models.TextField(verbose_name="説明")),
                ("algorithm_config", models.JSONField(verbose_name="アルゴリズム設定")),
                (
                    "target_user_ratio",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="対象ユーザー割合",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("active", "実行中"),
                            ("paused", "一時停止"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="開始日時")),
                ("end_date", models.DateTimeField(verbose_name="終了日時")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_experiments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "推薦実験",
                "verbose_name_plural": "推薦実験",
                "db_table": "recommendation_experiments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSimilarity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="類似度スコア",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="cosine", max_length=50, verbose_name="計算手法"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="計算日時"),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_user1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー1",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_user2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー2",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー類似度",
                "verbose_name_plural": "ユーザー類似度",
                "db_table": "user_similarities",
                "indexes": [
                    models.Index(
                        fields=["user1", "similarity_score"],
                        name="user_simila_user1_i_a12e09_idx",
                    ),
                    models.Index(
                        fields=["user2", "similarity_score"],
                        name="user_simila_user2_i_bda7ad_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="user_simila_calcula_19ed1b_idx"
                    ),
                ],
                "unique_together": {("user1", "user2", "calculation_method")},
            },
        ),
        migrations.CreateModel(
            name="UserRecommendationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("view", "閲覧"),
                            ("click", "クリック"),
                            ("join_request", "参加申請"),
                            ("join_success", "参加成功"),
                            ("dismiss", "却下"),
                            ("not_interested", "興味なし"),
                            ("bookmark", "ブックマーク"),
                            ("share", "シェア"),
                        ],
                        max_length=20,
                        verbose_name="フィードバックタイプ",
                    ),
                ),
                (
                    "recommendation_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="推薦スコア",
                    ),
                ),
                (
                    "recommendation_algorithm",
                    models.CharField(max_length=50, verbose_name="推薦アルゴリズム"),
                ),
                (
                    "recommendation_reasons",
                    models.JSONField(default=list, verbose_name="推薦理由"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="セッションID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedbacks",
                        to="circles.circle",
                        verbose_name="サークル",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー推薦フィードバック",
                "verbose_name_plural": "ユーザー推薦フィードバック",
                "db_table": "user_recommendation_feedbacks",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_recomm_user_id_cce447_idx",
                    ),
                    models.Index(
                        fields=["circle", "feedback_type"],
                        name="user_recomm_circle__b3e241_idx",
                    ),
                    models.Index(
                        fields=["recommendation_algorithm", "created_at"],
                        name="user_recomm_recomme_a220f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInteractionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view_circle", "サークル閲覧"),
                            ("view_profile", "プロフィール閲覧"),
                            ("join_request", "参加申請"),
                            ("join_approved", "参加承認"),
                            ("join_rejected", "参加拒否"),
                            ("leave_circle", "サークル退会"),
                            ("post_message", "メッセージ投稿"),
                            ("react_to_post", "投稿リアクション"),
                            ("create_event", "イベント作成"),
                            ("join_event", "イベント参加"),
                        ],
                        max_length=30,
                        verbose_name="アクションタイプ",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="滞在時間（秒）"
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(default=dict, verbose_name="コンテキストデータ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_history",
                        to="circles.circle",
                        verbose_name="サークル",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザーインタラクション履歴",
                "verbose_name_plural": "ユーザーインタラクション履歴",
                "db_table": "user_interaction_history",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_intera_user_id_54d3c5_idx",
                    ),
                    models.Index(
                        fields=["circle", "action_type"],
                        name="user_intera_circle__ca14d7_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="user_intera_action__6398f1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("ctr", "クリック率"),
                            ("conversion_rate", "コンバージョン率"),
                            ("precision_at_k", "Precision@K"),
                            ("diversity_score", "多様性スコア"),
                            ("novelty_score", "新規性スコア"),
                            ("coverage_rate", "カバレッジ率"),
                        ],
                        max_length=30,
                        verbose_name="メトリクスタイプ",
                    ),
                ),
                (
                    "algorithm_name",
                    models.CharField(max_length=50, verbose_name="アルゴリズム名"),
                ),
                ("metric_value", models.FloatField(verbose_name="メトリクス値")),
                (
                    "user_segment",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ユーザーセグメント",
                    ),
                ),
                ("measurement_date", models.DateField(verbose_name="測定日")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="recommendations.recommendationexperiment",
                        verbose_name="実験",
                    ),
                ),
            ],
            options={
                "verbose_name": "推薦メトリクス",
                "verbose_name_plural": "推薦メトリクス",
                "db_table": "recommendation_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_type", "algorithm_name", "measurement_date"],
                        name="recommendat_metric__97907f_idx",
                    ),
                    models.Index(
                        fields=["experiment", "metric_type"],
                        name="recommendat_experim_016945_idx",
                    ),
                ],
            },
        ),
    ]
