# Generated by Django 4.2.22 on 2025-06-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interests", "0003_alter_interest_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="カテゴリー名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "カテゴリー",
                "verbose_name_plural": "カテゴリー",
            },
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="サークル名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="アイコンURL",
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="カバー画像URL",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="タグ"),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(default=0, verbose_name="メンバー数"),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(default=0, verbose_name="投稿数"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="最終アクティビティ"
                    ),
                ),
                ("rules", models.TextField(blank=True, verbose_name="サークル規約")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "募集中"),
                            ("closed", "応募締切"),
                            ("full", "満員"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="募集状態",
                    ),
                ),
                (
                    "circle_type",
                    models.CharField(
                        choices=[
                            ("public", "公開"),
                            ("approval", "承認制"),
                            ("private", "非公開"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="サークルタイプ",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, verbose_name="プレミアムサークル"
                    ),
                ),
                (
                    "member_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="メンバー制限"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="非公開"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="circles",
                        to="circles.category",
                        verbose_name="カテゴリー",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_circles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        related_name="circles",
                        to="interests.interest",
                        verbose_name="興味・関心",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_circles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="オーナー",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークル",
                "verbose_name_plural": "サークル",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="CircleSearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "search_query",
                    models.CharField(max_length=200, verbose_name="検索クエリ"),
                ),
                (
                    "search_filters",
                    models.JSONField(default=dict, verbose_name="検索フィルター"),
                ),
                ("results_count", models.IntegerField(verbose_name="検索結果数")),
                (
                    "searched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="検索日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_search_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークル検索履歴",
                "verbose_name_plural": "サークル検索履歴",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_score",
                    models.FloatField(verbose_name="レコメンドスコア"),
                ),
                (
                    "recommendation_reason",
                    models.CharField(max_length=100, verbose_name="レコメンド理由"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=False, verbose_name="閲覧済み"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="circles.circle",
                        verbose_name="サークル",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークルレコメンデーション",
                "verbose_name_plural": "サークルレコメンデーション",
            },
        ),
        migrations.CreateModel(
            name="CirclePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "media_urls",
                    models.JSONField(
                        blank=True, default=list, verbose_name="メディアURL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="circles.circle",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークル投稿",
                "verbose_name_plural": "サークル投稿",
            },
        ),
        migrations.CreateModel(
            name="CircleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="説明")),
                ("start_datetime", models.DateTimeField(verbose_name="開始日時")),
                ("end_datetime", models.DateTimeField(verbose_name="終了日時")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="場所"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="circles.circle",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークルイベント",
                "verbose_name_plural": "サークルイベント",
            },
        ),
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("active", "参加中"),
                            ("rejected", "拒否"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "オーナー"),
                            ("admin", "管理者"),
                            ("member", "メンバー"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="役割",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="参加日時"
                    ),
                ),
                (
                    "application_message",
                    models.TextField(blank=True, verbose_name="申請メッセージ"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="拒否理由"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="circles.circle",
                        verbose_name="サークル",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークルメンバーシップ",
                "verbose_name_plural": "サークルメンバーシップ",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "circle")},
            },
        ),
        migrations.CreateModel(
            name="CircleInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(default=0.0, verbose_name="関連度スコア"),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="追加日時"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_interests",
                        to="circles.circle",
                        verbose_name="サークル",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_interests",
                        to="interests.interest",
                        verbose_name="興味",
                    ),
                ),
            ],
            options={
                "verbose_name": "サークルの興味",
                "verbose_name_plural": "サークルの興味",
                "unique_together": {("circle", "interest")},
            },
        ),
        migrations.CreateModel(
            name="CircleChatRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_read",
                    models.DateTimeField(auto_now=True, verbose_name="最終既読時間"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reads",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_chat_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "チャット既読",
                "verbose_name_plural": "チャット既読",
                "indexes": [
                    models.Index(
                        fields=["user", "circle", "last_read"],
                        name="circles_cir_user_id_e62c39_idx",
                    ),
                    models.Index(
                        fields=["circle", "last_read"],
                        name="circles_cir_circle__971495_idx",
                    ),
                ],
                "unique_together": {("user", "circle")},
            },
        ),
        migrations.CreateModel(
            name="CircleChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="メッセージ内容")),
                (
                    "media_urls",
                    models.JSONField(
                        blank=True, default=list, verbose_name="メディアURL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False, verbose_name="システムメッセージ"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="編集済み"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="circles.circle",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="circles.circlechat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "サークルチャット",
                "verbose_name_plural": "サークルチャット",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["circle", "-created_at"],
                        name="circles_cir_circle__f87430_idx",
                    ),
                    models.Index(
                        fields=["sender", "circle"],
                        name="circles_cir_sender__a1d876_idx",
                    ),
                    models.Index(
                        fields=["circle", "is_system_message"],
                        name="circles_cir_circle__d5824d_idx",
                    ),
                ],
            },
        ),
    ]
