# Generated by Django 4.2.22 on 2025-06-28 04:12

from django.db import migrations, models
import django.db.models.deletion


def clear_circle_interests(apps, schema_editor):
    CircleInterest = apps.get_model('circles', 'CircleInterest')
    CircleInterest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_circle_interests),
        migrations.RemoveField(
            model_name='circle',
            name='interests',
        ),
        migrations.DeleteModel(
            name='CircleInterest',
        ),
        migrations.CreateModel(
            name='CircleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_interests', to='circles.circle', verbose_name='サークル')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_interests', to='interests.interesttag', verbose_name='興味')),
            ],
            options={
                'verbose_name': 'サークルの興味・関心',
                'verbose_name_plural': 'サークルの興味・関心',
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='interests',
            field=models.ManyToManyField(related_name='circles', through='circles.CircleInterest', to='interests.interesttag', verbose_name='興味・関心'),
        ),
    ]
