# Generated by Django 4.2.22 on 2025-06-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "テキスト"),
                            ("emotion", "感情"),
                            ("support_request", "サポート要請"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="メッセージタイプ",
                    ),
                ),
                (
                    "emotion_tag",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="感情タグ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="circles.circle",
                        verbose_name="サークル",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat_messages.message",
                        verbose_name="返信先",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="送信者",
                    ),
                ),
            ],
            options={
                "verbose_name": "メッセージ",
                "verbose_name_plural": "メッセージ",
                "db_table": "messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
