# Generated by Django 4.2.22 on 2025-06-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "無料プラン"),
                            ("basic", "ベーシックプラン"),
                            ("premium", "プレミアムプラン"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "アクティブ"),
                            ("cancelled", "キャンセル"),
                            ("expired", "期限切れ"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金額"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="JPY", max_length=3, verbose_name="通貨"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "処理中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                            ("refunded", "返金済み"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="支払い方法"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="取引ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                        verbose_name="サブスクリプション",
                    ),
                ),
            ],
            options={
                "verbose_name": "支払い履歴",
                "verbose_name_plural": "支払い履歴",
                "ordering": ["-created_at"],
            },
        ),
    ]
