# Generated by Django 4.2.22 on 2025-06-08 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hobby", "趣味"),
                            ("lifestyle", "ライフスタイル"),
                            ("emotion", "感情"),
                            ("skill", "スキル"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_official", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interests",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        choices=[
                            (1, "少し興味がある"),
                            (2, "興味がある"),
                            (3, "とても興味がある"),
                            (4, "大好き"),
                            (5, "熱中している"),
                        ]
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interests",
                        to="interests.interest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_interests",
                "ordering": ["-intensity", "-added_at"],
                "unique_together": {("user", "interest")},
            },
        ),
    ]
