# Generated by Django 4.2.22 on 2025-06-08 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinterest",
            options={
                "verbose_name": "ユーザー興味関心",
                "verbose_name_plural": "ユーザー興味関心",
            },
        ),
        migrations.RemoveField(
            model_name="userinterest",
            name="intensity",
        ),
        migrations.AlterField(
            model_name="userinterest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userinterest",
            name="interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="interests.interest"
            ),
        ),
        migrations.AlterField(
            model_name="userinterest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="userinterest",
            table=None,
        ),
    ]
