# Generated by Django 4.2.22 on 2025-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interests", "0002_alter_userinterest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="category",
            field=models.CharField(
                choices=[
                    ("gaming", "🎮 ゲーム"),
                    ("learning", "📚 学習・知識"),
                    ("creative", "🎨 クリエイティブ"),
                    ("sports", "🏃\u200d♂️ スポーツ"),
                    ("food", "🍳 料理・グルメ"),
                    ("travel", "🌍 旅行・アウトドア"),
                    ("lifestyle", "💰 ライフスタイル"),
                    ("entertainment", "🎭 エンターテイメント"),
                    ("technical", "🔬 技術・専門"),
                    ("business", "🎯 ビジネス・キャリア"),
                    ("wellness", "🧠 自己開発・ウェルネス"),
                ],
                max_length=20,
            ),
        ),
    ]
