# Generated by Django 4.2.22 on 2025-06-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interests", "0004_tag_usertag"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="カテゴリ名"
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="タイプ")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "icon_url",
                    models.URLField(blank=True, null=True, verbose_name="アイコンURL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "興味関心カテゴリ",
                "verbose_name_plural": "興味関心カテゴリ",
                "db_table": "interest_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InterestSubcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="サブカテゴリ名"),
                ),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="interests.interestcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "興味関心サブカテゴリ",
                "verbose_name_plural": "興味関心サブカテゴリ",
                "db_table": "interest_subcategories",
                "ordering": ["category__name", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="タグ名")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用回数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="interests.interestsubcategory",
                        verbose_name="サブカテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "興味関心タグ",
                "verbose_name_plural": "興味関心タグ",
                "db_table": "interest_tags",
                "ordering": [
                    "-usage_count",
                    "subcategory__category__name",
                    "subcategory__name",
                    "name",
                ],
                "unique_together": {("subcategory", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserInterestProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        choices=[
                            (1, "少し興味がある"),
                            (2, "興味がある"),
                            (3, "かなり興味がある"),
                            (4, "とても興味がある"),
                            (5, "非常に興味がある"),
                        ],
                        default=3,
                        verbose_name="強度",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="追加日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interests.interestcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interests.interestsubcategory",
                        verbose_name="サブカテゴリ",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interests.interesttag",
                        verbose_name="タグ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchical_interests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー興味関心プロフィール",
                "verbose_name_plural": "ユーザー興味関心プロフィール",
                "db_table": "user_interest_profiles",
                "ordering": ["-intensity", "-added_at"],
                "unique_together": {("user", "tag")},
            },
        ),
    ]
