# Generated by Django 4.2.22 on 2025-06-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_interestcategory_interestsubcategory_interesttag_and_more'),
    ]

    operations = [
    ]
