# Generated by Django 4.2.22 on 2025-06-12 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_default_category(apps, schema_editor):
    """デフォルトカテゴリを作成"""
    InterestCategory = apps.get_model('interests', 'InterestCategory')
    
    default_category, created = InterestCategory.objects.get_or_create(
        name='その他',
        defaults={
            'id': str(uuid.uuid4()),
            'type': 'other',
            'description': 'カテゴリ未分類の興味関心',
            'icon_url': None,
        }
    )
    return default_category


def migrate_existing_profiles(apps, schema_editor):
    """既存のUserInterestProfileにデフォルト値を設定"""
    UserInterestProfile = apps.get_model('interests', 'UserInterestProfile')
    InterestCategory = apps.get_model('interests', 'InterestCategory')
    
    # デフォルトカテゴリを作成
    default_category = create_default_category(apps, schema_editor)
    
    # category が null の既存レコードを更新
    UserInterestProfile.objects.filter(category__isnull=True).update(
        category=default_category,
        level=3  # 既存データはタグレベルとして扱う
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0006_auto_20250612_2102'),
    ]

    operations = [
        # levelフィールドを追加
        migrations.AddField(
            model_name='userinterestprofile',
            name='level',
            field=models.IntegerField(
                choices=[(1, 'カテゴリレベル'), (2, 'サブカテゴリレベル'), (3, 'タグレベル')],
                default=3,
                verbose_name='選択レベル'
            ),
        ),
        
        # 既存データの移行
        migrations.RunPython(migrate_existing_profiles, reverse_code=migrations.RunPython.noop),
        
        # categoryフィールドを必須に変更
        migrations.AlterField(
            model_name='userinterestprofile',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='interests.interestcategory',
                verbose_name='カテゴリ'
            ),
        ),
        
        # tagフィールドをnull許可に変更
        migrations.AlterField(
            model_name='userinterestprofile',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='interests.interesttag',
                verbose_name='タグ'
            ),
        ),
        
        # intensityフィールドを削除
        migrations.RemoveField(
            model_name='userinterestprofile',
            name='intensity',
        ),
        
        # unique_togetherを削除（tagがnullableになるため）
        migrations.AlterUniqueTogether(
            name='userinterestprofile',
            unique_together=set(),
        ),
        
        # orderingを更新
        migrations.AlterModelOptions(
            name='userinterestprofile',
            options={
                'ordering': ['-added_at'],
                'verbose_name': 'ユーザー興味関心プロフィール',
                'verbose_name_plural': 'ユーザー興味関心プロフィール'
            },
        ),
    ]
