# Generated by Django 4.2.22 on 2025-06-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interests", "0007_auto_20250612_2148"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interestsubcategory",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "興味関心サブカテゴリ",
                "verbose_name_plural": "興味関心サブカテゴリ",
            },
        ),
        migrations.AlterModelOptions(
            name="interesttag",
            options={
                "ordering": ["subcategory", "-usage_count", "name"],
                "verbose_name": "興味関心タグ",
                "verbose_name_plural": "興味関心タグ",
            },
        ),
        migrations.AlterField(
            model_name="interestcategory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="interestcategory",
            name="type",
            field=models.CharField(
                choices=[
                    ("hobby", "趣味"),
                    ("skill", "スキル"),
                    ("career", "キャリア"),
                    ("lifestyle", "ライフスタイル"),
                ],
                max_length=20,
                verbose_name="タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="interestsubcategory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="interesttag",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="説明"),
        ),
    ]
