# Generated by Django 4.2.22 on 2025-06-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interests", "0006_remove_tag_usertag"),
        ("interests", "0007_auto_20250612_2148"),
    ]

    operations = []
