# Generated by Django 4.2.22 on 2025-06-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0008_alter_interestsubcategory_options_and_more'),
        ('circles', '0002_alter_circle_interests_alter_circleinterest_interest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
